export const salariedFields = [
  {
    label: "Name of the Company",
    placeholder: "Enter Company Name",
    apiKey: "employer",
    validators: undefined,
    type: "text",
    required: true,
    regex: undefined,
  },
  {
    label: "Designation",
    placeholder: "Enter Designation",
    apiKey: "designation",
    validators: undefined,
    type: "text",
    required: true,
    regex: undefined,
  },
  {
    label: "Total year of Experience",
    placeholder: "Enter number of years",
    apiKey: "experience_in_year",
    validators: "positive_number",
    type: "number",
    required: true,
    regex: undefined,
  },
  {
    label: "Monthly Income",
    placeholder: "Enter Monthly Income",
    apiKey: "monthly_income",
    validators: "positive_number",
    type: "number",
    required: true,
    regex: undefined,
  },
  {
    label: "Time at Current Job (in years)",
    placeholder: "Enter Number of Years",
    apiKey: "current_job_years",
    validators: "positive_number",
    type: "number",
    required: true,
    regex: undefined,
  },
  {
    label: "Profession",
    placeholder: "Select Profession",
    apiKey: "profession",
    type: "select",
    required: false,
    options: [
      { label: "Chiropractor", value: "CHIROPRACTOR" },
      { label: "Dentist", value: "DENTIST" },
      { label: "Dietitian or Nutritionist", value: "DIETITIAN_NUTRITIONIST" },
      { label: "Optometrist", value: "OPTOMETRIST" },
      { label: "Pharmacist", value: "PHARMACIST" },
      { label: "Physician", value: "PHYSICIAN" },
      { label: "Physician Assistant", value: "PHYSICIAN_ASSISTANT" },
      { label: "Podiatrist", value: "PODIATRIST" },
      { label: "Registered Nurse", value: "REGISTERED_NURSE" },
      { label: "Therapist", value: "THERAPIST" },
      { label: "Veterinarian", value: "VETERINARIAN" },
      {
        label: "Health Technologist or Technician",
        value: "HEALTH_TECHNOLOGIST_TECHNICIAN",
      },
      {
        label: "Other Healthcare Practitioners and Technical Occupation",
        value: "OTHER_HEALTHCARE_PRACTITIONERS",
      },
      {
        label: "Nursing, Psychiatric, or Home Health Aide",
        value: "NURSING_PSYCHIATRIC_HOME_HEALTH_AIDE",
      },
      {
        label: "Occupational and Physical Therapist Assistant or Aide",
        value: "OCCUPATIONAL_PHYSICAL_THERAPIST_ASSISTANT_AIDE",
      },
      {
        label: "Other Healthcare Support Occupation",
        value: "OTHER_HEALTHCARE_SUPPORT_OCCUPATION",
      },
      { label: "Chief Executive", value: "CHIEF_EXECUTIVE" },
      {
        label: "General and Operations Manager",
        value: "GENERAL_OPERATIONS_MANAGER",
      },
      {
        label:
          "Advertising, Marketing, Promotions, Public Relations, and Sales Manager",
        value: "ADVERTISING_MARKETING_SALES_MANAGER",
      },
      {
        label: "Operations Specialties Manager (e.g., IT or HR Manager)",
        value: "OPERATIONS_SPECIALTIES_MANAGER",
      },
      { label: "Construction Manager", value: "CONSTRUCTION_MANAGER" },
      { label: "Engineering Manager", value: "ENGINEERING_MANAGER" },
      { label: "Accountant, Auditor", value: "ACCOUNTANT_AUDITOR" },
      {
        label: "Business Operations or Financial Specialist",
        value: "BUSINESS_OPERATIONS_FINANCIAL_SPECIALIST",
      },
      { label: "Business Owner", value: "BUSINESS_OWNER" },
      {
        label: "Other Business, Executive, Management, Financial Occupation",
        value: "OTHER_BUSINESS_EXECUTIVE_MANAGEMENT_FINANCIAL_OCCUPATION",
      },
      {
        label: "Architect, Surveyor, or Cartographer",
        value: "ARCHITECT_SURVEYOR_CARTOGRAPHER",
      },
      { label: "Engineer", value: "ENGINEER" },
      {
        label: "Other Architecture and Engineering Occupation",
        value: "OTHER_ARCHITECTURE_ENGINEERING_OCCUPATION",
      },
      {
        label: "Postsecondary Teacher (e.g., College Professor)",
        value: "POSTSECONDARY_TEACHER",
      },
      {
        label: "Primary, Secondary, or Special Education School Teacher",
        value: "EDUCATION_SCHOOL_TEACHER",
      },
      {
        label: "Other Teacher or Instructor",
        value: "OTHER_TEACHER_INSTRUCTOR",
      },
      {
        label: "Other Education, Training, and Library Occupation",
        value: "OTHER_EDUCATION_TRAINING_LIBRARY_OCCUPATION",
      },
      {
        label: "Arts, Design, Entertainment, Sports, and Media Occupations",
        value: "ARTS_DESIGN_ENTERTAINMENT_SPORTS_MEDIA_OCCUPATIONS",
      },
      {
        label: "Computer Specialist, Mathematical Science",
        value: "COMPUTER_SPECIALIST_MATHEMATICAL_SCIENCE",
      },
      {
        label:
          "Counselor, Social Worker, or Other Community and Social Service Specialist",
        value: "COUNSELOR_SOCIAL_WORKER_COMMUNITY_SERVICE_SPECIALIST",
      },
      { label: "Lawyer, Judge", value: "LAWYER_JUDGE" },
      {
        label:
          "Life Scientist (e.g., Animal, Food, Soil, or Biological Scientist, Zoologist)",
        value: "LIFE_SCIENTIST",
      },
      {
        label:
          "Physical Scientist (e.g., Astronomer, Physicist, Chemist, Hydrologist)",
        value: "PHYSICAL_SCIENTIST",
      },
      {
        label:
          "Religious Worker (e.g., Clergy, Director of Religious Activities or Education)",
        value: "RELIGIOUS_WORKER",
      },
      {
        label: "Social Scientist and Related Worker",
        value: "SOCIAL_SCIENTIST",
      },
      {
        label: "Other Professional Occupation",
        value: "OTHER_PROFESSIONAL_OCCUPATION",
      },
      {
        label: "Supervisor of Administrative Support Workers",
        value: "ADMINISTRATIVE_SUPPORT_SUPERVISOR",
      },
      { label: "Financial Clerk", value: "FINANCIAL_CLERK" },
      {
        label: "Secretary or Administrative Assistant",
        value: "SECRETARY_ADMINISTRATIVE_ASSISTANT",
      },
      {
        label: "Material Recording, Scheduling, and Dispatching Worker",
        value: "MATERIAL_RECORDING_SCHEDULING_DISPATCHING_WORKER",
      },
      {
        label: "Other Office and Administrative Support Occupation",
        value: "OTHER_OFFICE_ADMINISTRATIVE_SUPPORT_OCCUPATION",
      },
      {
        label:
          "Protective Service (e.g., Fire Fighting, Police Officer, Correctional Officer)",
        value: "PROTECTIVE_SERVICE",
      },
      { label: "Chef or Head Cook", value: "CHEF_HEAD_COOK" },
      {
        label: "Cook or Food Preparation Worker",
        value: "COOK_FOOD_PREPARATION_WORKER",
      },
      {
        label:
          "Food and Beverage Serving Worker (e.g., Bartender, Waiter, Waitress)",
        value: "FOOD_BEVERAGE_SERVING_WORKER",
      },
      {
        label: "Building and Grounds Cleaning and Maintenance",
        value: "BUILDING_GROUNDS_CLEANING_MAINTENANCE",
      },
      {
        label:
          "Personal Care and Service (e.g., Hairdresser, Flight Attendant, Concierge)",
        value: "PERSONAL_CARE_SERVICE",
      },
      {
        label: "Sales Supervisor, Retail Sales",
        value: "SALES_SUPERVISOR_RETAIL_SALES",
      },
      { label: "Retail Sales Worker", value: "RETAIL_SALES_WORKER" },
      { label: "Insurance Sales Agent", value: "INSURANCE_SALES_AGENT" },
      { label: "Sales Representative", value: "SALES_REPRESENTATIVE" },
      { label: "Real Estate Sales Agent", value: "REAL_ESTATE_SALES_AGENT" },
      {
        label: "Other Services Occupation",
        value: "OTHER_SERVICES_OCCUPATION",
      },
      {
        label:
          "Construction and Extraction (e.g., Construction Laborer, Electrician)",
        value: "CONSTRUCTION_EXTRACTION",
      },
      {
        label: "Farming, Fishing, and Forestry",
        value: "FARMING_FISHING_FORESTRY",
      },
      {
        label: "Installation, Maintenance, and Repair",
        value: "INSTALLATION_MAINTENANCE_REPAIR",
      },
      { label: "Production Occupations", value: "PRODUCTION_OCCUPATIONS" },
      {
        label:
          "Other Agriculture, Maintenance, Repair, and Skilled Crafts Occupation",
        value: "OTHER_AGRICULTURE_MAINTENANCE_REPAIR_SKILLED_CRAFTS_OCCUPATION",
      },
      {
        label: "Aircraft Pilot or Flight Engineer",
        value: "AIRCRAFT_PILOT_FLIGHT_ENGINEER",
      },
      {
        label:
          "Motor Vehicle Operator (e.g., Ambulance, Bus, Taxi, or Truck Driver)",
        value: "MOTOR_VEHICLE_OPERATOR",
      },
      {
        label: "Other Transportation Occupation",
        value: "OTHER_TRANSPORTATION_OCCUPATION",
      },
      { label: "Military", value: "MILITARY" },
      { label: "Homemaker", value: "HOMEMAKER" },
      { label: "Other Occupation", value: "OTHER_OCCUPATION" },
      { label: "Don't Know", value: "DONTS_KNOW" },
      { label: "Not Applicable", value: "NOT_APPLICABLE" },
    ],
  },
  {
    label: "Office Address",
    placeholder: "Enter Office Address",
    apiKey: "address_line_1",
    validators: undefined,
    type: "textarea",
    required: true,
    regex: undefined,
  },
  {
    label: "Land Mark",
    placeholder: "Enter Land Mark",
    apiKey: "landmark",
    validators: undefined,
    type: "text",
    required: false,
    regex: undefined,
  },
  {
    label: "PinCode",
    placeholder: "Enter Pincode",
    apiKey: "pincode",
    validators: "pincode",
    type: "text",
    required: true,
    regex: undefined,
  },
  {
    label: "City",
    placeholder: "Enter City",
    apiKey: "city",
    validators: undefined,
    type: "text",
    required: true,
    regex: undefined,
  },
  {
    label: "State",
    placeholder: "Select State",
    apiKey: "state",
    validators: undefined,
    type: "select",
    required: true,
    regex: undefined,
    options: [
      { label: "Andhra Pradesh", value: "Andhra Pradesh" },
      { label: "Arunachal Pradesh", value: "Arunachal Pradesh" },
      { label: "Assam", value: "Assam" },
      { label: "Bihar", value: "Bihar" },
      { label: "Chhattisgarh", value: "Chhattisgarh" },
      { label: "Goa", value: "Goa" },
      { label: "Gujarat", value: "Gujarat" },
      { label: "Haryana", value: "Haryana" },
      { label: "Himachal Pradesh", value: "Himachal Pradesh" },
      { label: "Jharkhand", value: "Jharkhand" },
      { label: "Karnataka", value: "Karnataka" },
      { label: "Kerala", value: "Kerala" },
      { label: "Madhya Pradesh", value: "Madhya Pradesh" },
      { label: "Maharashtra", value: "Maharashtra" },
      { label: "Manipur", value: "Manipur" },
      { label: "Meghalaya", value: "Meghalaya" },
      { label: "Mizoram", value: "Mizoram" },
      { label: "Nagaland", value: "Nagaland" },
      { label: "Odisha", value: "Odisha" },
      { label: "Punjab", value: "Punjab" },
      { label: "Rajasthan", value: "Rajasthan" },
      { label: "Sikkim", value: "Sikkim" },
      { label: "Tamil Nadu", value: "Tamil Nadu" },
      { label: "Telangana", value: "Telangana" },
      { label: "Tripura", value: "Tripura" },
      { label: "Uttarakhand", value: "Uttarakhand" },
      { label: "Uttar Pradesh", value: "Uttar Pradesh" },
      { label: "West Bengal", value: "West Bengal" },
    ],
  },
  {
    label: "STD Code",
    placeholder: "Enter STD Code",
    apiKey: "std_code",
    validators: undefined,
    type: "text",
    required: false,
    regex: undefined,
  },
  {
    label: "Office Phone Number",
    placeholder: "Enter Office Phone Number",
    apiKey: "phone_number",
    validators: "phone_number",
    type: "text",
    required: false,
    regex: undefined,
  },
  {
    label: "Office Extension",
    placeholder: "Enter Office Extension",
    apiKey: "office_extension",
    validators: undefined,
    type: "text",
    required: false,
    regex: undefined,
  },
  {
    label: "Official Email ID",
    placeholder: "Enter Official Email ID",
    apiKey: "work_email",
    validators: "email_id",
    type: "text",
    required: true,
    regex: undefined,
  },
  {
    label: "Alternative Phone Number",
    placeholder: "Enter Alternative Phone Number",
    apiKey: "work_phone_number",
    validators: "phone_number",
    type: "text",
    required: false,
    regex: undefined,
  },
];
